import type { Metadata } from "next";
import { Exo_2 } from "next/font/google";
import "./globals.css";
import { NavigationProvider } from "@/context";

// Load Poppins from Google Fonts
const poppins = Exo_2({
  subsets: ["latin"],
  weight: ["400"], // only allowed weight for Exo_2
  variable: "--font-poppins", // creates a CSS variable for Tailwind/theme
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <NavigationProvider>{children}</NavigationProvider>
      </body>
    </html>
  );
}
